apiVersion: v1
kind: Service
metadata:
  name: infinispan-service
  labels:
    app: infinispan
spec:
  ports:
    - protocol: TCP
      port: 11222
      targetPort: 11222
  selector:
    app: infinispan
