apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  labels:
    app: postgres
data:
  POSTGRESQL_USER: postgres
  POSTGRESQL_PASSWORD: admin
  POSTGRESQL_HOST: postgres-service
  POSTGRESQL_PORT: "5432"
  POSTGRESQL_DATABASE: postgres
  POSTGRESQL_JNDI: java:jboss/datasources/PostgreSQLDS
