
= getting-started

The `getting-started` project is a simple Jakarta EE application with a HTTP endpoint that is running in
https://wildfly.org[WildFly].

The `src/main` folder contains a simple 'Hello world' style Jakarta EE application using JAX-RS.

== Building the application

To run the application, you use Maven:

[source,shell]
----
mvn clean package
----

Maven will compile the application, provision a WildFly server
The WildFly server is created in `target/server` with the application deployed in it.

== Running the application

To run the application, run the commands:

[source,shell]
----
cd target/server
./bin/standalone.sh
----

Once WildFly is running, the application can be accessed at http://localhost:8080/

== Testing the application

To run integration tests to verify the application, you use Maven:

[source,shell]
----
mvn clean package verify
----

Tests in `src/test` are run against the server in `target/server`.

== Build Docker Image

[source,shell]
----
$ podman build -t myapp:latest .
----

== Run the Docker Image

[source,shell]
----
podman run --rm -p 8080:8080 -p 9990:9990 --name=myapp myapp
----

== Pushing to local Image Registry

Tag thr image:
[source,shell]
----
podman tag myapp localhost:5000/myapp
----

Start a local registry:
[source,shell]
----
podman run --rm -p 5000:5000 --name registry registry:latest
podman run --rm -p 5000:5000 --volume ~/.registry/storage:/var/lib/registry registry:latest
----

[source,shell]
----
podman push localhost:5000/myapp --tls-verify=false
----

== PostgreSQL

Start PostgreSQL:

[source,shell]
----
podman run --rm --name my-postgres -p 5432:5432 -e POSTGRES_PASSWORD=admin -e POSTGRES_USER=postgres -e POSTGRES_DB=postgres postgres
----

Add some data to PostgreSQL:

[source,bash]
----
podman exec -it my-postgres bash
psql -U postgres
CREATE TABLE TEST_TABLE (
  id SERIAL PRIMARY KEY,
  SOME_FIELD1 VARCHAR (50) NOT NULL,
  SOME_FIELD2 VARCHAR (50) NOT NULL
);
insert into test_table values (1, 'prova1', 'prova1');
insert into test_table values (2, 'prova2', 'prova2');
insert into test_table values (3, 'prova3', 'prova3');
commit;
select * from TEST_TABLE;
quit
exit
----

[source,shell]
----
export POSTGRESQL_USER=postgres
export POSTGRESQL_PASSWORD=admin
export POSTGRESQL_HOST=localhost
export POSTGRESQL_PORT=5432
export POSTGRESQL_DATABASE=postgres
export POSTGRESQL_JNDI=java:jboss/datasources/PostgreSQLDS

mvn clean install

./target/server/bin/standalone.sh

curl -X POST http://localhost:8080/hello/test-table/insert/somedata1/somedata2

curl http://localhost:8080/hello/test-table/list
----


[source,shell]
----
minikube config set rootless true
minikube start --driver=podman --container-runtime=cri-o

kubectl port-forward svc/postgres-external 5432:5432
----

[source,shell]
----
podman pull docker.io/infinispan/server:latest

# -p 11222:11222
podman run --rm --net=host -e USER="admin" -e PASS="123pippobaudo" docker.io/infinispan/server:latest

podman run --rm --net=host -it docker.io/infinispan/cli:latest 
  connect http://admin:123pippobaudo@0.0.0.0:11222
  ls caches
podman run --rm --net=host -it docker.io/infinispan/cli:latest 
  connect http://0.0.0.0:11222 -u admin -p 123pippobaudo
  ls caches
----

try:
[source,xml]
----
<subsystem xmlns="urn:jboss:domain:infinispan:12.0">
    <remote-cache-containers>
        <remote-cache-container name="infinispan-remote-container" default-remote-cluster="infinispan-cluster" module="org.infinispan.client.hotrod">
            <remote-cluster name="infinispan-cluster">
                <remote-server outbound-socket-binding="infinispan-server"/>
            </remote-cluster>
        </remote-cache-container>
    </remote-cache-containers>
</subsystem>

<socket-binding-group name="standard-sockets" default-interface="public" port-offset="${jboss.socket.binding.port-offset:0}">
    <outbound-socket-binding name="infinispan-server">
        <remote-destination host="infinispan-server-hostname" port="11222"/>
    </outbound-socket-binding>
</socket-binding-group>

<subsystem xmlns="urn:jboss:domain:distributable-web:2.0">
    <hotrod-session-management cache-container="infinispan-remote-container" client-ssl-context="none"/>
</subsystem>
----

== Resources

* https://wildfly.org[WildFly]
* https://docs.wildfly.org[WildFly Documentation]
